/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package absensi;

/**
 *
 * @author Afandi-Nat
 */
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import net.proteanit.sql.DbUtils;

public class FormAbsensi extends javax.swing.JFrame {

    Connection connj = null;
    ResultSet rsj = null;
    PreparedStatement pstj = null;
            
    public FormAbsensi() {
        initComponents();
        
        connj = absensi.KoneksiDB.ConnectDb();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Txt_IdKaryawan = new javax.swing.JTextField();
        Txt_Nama = new javax.swing.JTextField();
        Btn_Masuk = new javax.swing.JButton();
        Btn_Batal = new javax.swing.JButton();
        Btn_Cari = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Absensi");

        jLabel1.setText("ID Karyawan");

        jLabel2.setText("Nama");

        Btn_Masuk.setText("Masuk");
        Btn_Masuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_MasukActionPerformed(evt);
            }
        });

        Btn_Batal.setText("Batal");
        Btn_Batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_BatalActionPerformed(evt);
            }
        });

        Btn_Cari.setText("Cari");
        Btn_Cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(Txt_IdKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn_Cari))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Btn_Masuk)
                                .addGap(18, 18, 18)
                                .addComponent(Btn_Batal))
                            .addComponent(Txt_Nama, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Txt_IdKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Cari))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Txt_Nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Masuk)
                    .addComponent(Btn_Batal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_CariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CariActionPerformed
        if(Txt_IdKaryawan.getText().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane,"Silahkan Masukan ID Karyawan");
        } 
        else
        {
            Connection conn = null;
            Statement stmt = null;
            String id = Txt_IdKaryawan.getText();
            try
            {
                conn = absensi.KoneksiDB.ConnectDb();
                stmt = connj.createStatement();
                String query = "select nama from karyawan where id = '"+id+"';";
                
                ResultSet rs = stmt.executeQuery(query);
                while(rs.next())
                {
                    Txt_Nama.setText(rs.getString("nama"));
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_Btn_CariActionPerformed

    private void Btn_MasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_MasukActionPerformed
        // TODO add your handling code here:
        Connection connj = null;
        Statement stmj = null;
        
        String id = Txt_IdKaryawan.getText();
        try 
        {
            connj = absensi.KoneksiDB.ConnectDb();
            stmj = connj.createStatement();
            String query = "select nama from karyawan where id ='"+id+"';";
            
            ResultSet rs = stmj.executeQuery(query);
            
            while(rs.next()){
                Txt_Nama.setText(rs.getString("nama"));
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
        if(Txt_Nama.getText().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Silahkan Masukan ID Karyawan");
        }
        else
        {
            Connection conn = null;
            Statement stmt = null;
            
            try{
                conn = absensi.KoneksiDB.ConnectDb();
                stmt = conn.createStatement();
                
                stmt.executeUpdate("update karyawan set status ='Masuk',kehadiran=kehadiran + 1 where id ='"+id+"';");
                JOptionPane.showMessageDialog(null,"Karyawan " + Txt_Nama.getText() + "masuk.");
            }
            catch(Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
                    
             
        }
    }//GEN-LAST:event_Btn_MasukActionPerformed

    private void Btn_BatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_BatalActionPerformed
        this.dispose();
    }//GEN-LAST:event_Btn_BatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAbsensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAbsensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAbsensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAbsensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAbsensi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Batal;
    private javax.swing.JButton Btn_Cari;
    private javax.swing.JButton Btn_Masuk;
    private javax.swing.JTextField Txt_IdKaryawan;
    private javax.swing.JTextField Txt_Nama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
