/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * fInputNilai.java
 *
 * Created on 12 Jun 13, 20:02:22
 */

package FACE;

import DB.Database;
import java.sql.SQLException;
import java.util.HashMap;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author Btrans
 */
public class fCetakNilai extends javax.swing.JDialog {

    /** Creates new form fInputNilai */
    public fCetakNilai(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        fambilMK();
        fambilTA();
        tampilData();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        txtKeterangan = new javax.swing.JLabel();
        txtMK = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtTA = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelData = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        cmdCetak = new javax.swing.JButton();
        cmdTutup = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtDosen = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jTabbedPane2.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane2.setForeground(new java.awt.Color(102, 102, 102));
        jTabbedPane2.setFocusable(false);
        jTabbedPane2.setFont(new java.awt.Font("Tahoma", 1, 14));

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));

        txtKeterangan.setBackground(new java.awt.Color(204, 255, 255));
        txtKeterangan.setFont(new java.awt.Font("Tahoma", 1, 12));
        txtKeterangan.setForeground(new java.awt.Color(102, 102, 102));
        txtKeterangan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtKeterangan.setText("[ Jumlah data : 20 ]");
        txtKeterangan.setOpaque(true);

        txtMK.setFont(new java.awt.Font("Tahoma", 0, 12));
        txtMK.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        txtMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMKActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Tahun Ajaran");

        txtTA.setFont(new java.awt.Font("Tahoma", 0, 12));
        txtTA.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        txtTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTAActionPerformed(evt);
            }
        });

        tabelData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelData);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Pilih Matakuliah");

        cmdCetak.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmdCetak.setForeground(new java.awt.Color(102, 102, 102));
        cmdCetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RESS/cetak-data.png"))); // NOI18N
        cmdCetak.setText("Cetak Data");
        cmdCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCetakActionPerformed(evt);
            }
        });

        cmdTutup.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmdTutup.setForeground(new java.awt.Color(102, 102, 102));
        cmdTutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RESS/Button-Turn-Off-icon.png"))); // NOI18N
        cmdTutup.setText("Tutup");
        cmdTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdTutupActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Pilih Dosen");

        txtDosen.setFont(new java.awt.Font("Tahoma", 0, 12));
        txtDosen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        txtDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDosenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtKeterangan, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtTA, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdCetak)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdTutup))
                    .addComponent(txtMK, 0, 436, Short.MAX_VALUE)
                    .addComponent(txtDosen, 0, 436, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMK, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTA, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdCetak, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdTutup, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane2.addTab("Cetak Laporan Nilai Per Matakuliah - Per Semester", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelDataMouseClicked

    }//GEN-LAST:event_tabelDataMouseClicked

    private void cmdCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCetakActionPerformed
        try
        {
            JRDataSource ds = null;
            dbku.bukaKoneksi();
            dbku.perintah.executeQuery("SELECT * FROM nilai,mahasiswa,tahunajar,dosen,matakuliah WHERE (nilai.n_ta_id='"+kodeTA[txtTA.getSelectedIndex()]+"' and nilai.n_ds_id='"+kodeDosen[txtDosen.getSelectedIndex()]+"' and nilai.n_mk_id='"+kodeMK[txtMK.getSelectedIndex()]+"' and mahasiswa.mhs_id=nilai.n_mhs_id and tahunajar.ta_id=nilai.n_ta_id and dosen.ds_id=nilai.n_ds_id and matakuliah.mk_id=nilai.n_mk_id)");
            dbku.hasil = dbku.perintah.getResultSet();
            ds = new JRResultSetDataSource(dbku.hasil);
            JasperPrint print = JasperFillManager.fillReport("src/lap/lapNilaiPerMK.jasper", new HashMap(), ds);
            JRViewer aview = new JRViewer(print);
            BoxPrint bp = new BoxPrint(this, true, aview);
            bp.tampilkan();

            dbku.tutupKoneksi();
        }
        catch(JRException e){JOptionPane.showMessageDialog(rootPane, e.getMessage());}
        catch(Exception e){JOptionPane.showMessageDialog(rootPane, e.getMessage());}
    }//GEN-LAST:event_cmdCetakActionPerformed

    private void txtMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMKActionPerformed
        tampilData();
    }//GEN-LAST:event_txtMKActionPerformed

    private void txtTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTAActionPerformed
        tampilData();
    }//GEN-LAST:event_txtTAActionPerformed

    private void cmdTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdTutupActionPerformed
        dispose();
    }//GEN-LAST:event_cmdTutupActionPerformed

    private void txtDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDosenActionPerformed
        tampilData();
    }//GEN-LAST:event_txtDosenActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                fCetakNilai dialog = new fCetakNilai(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void tampilData(){
        String[] kolom = {"No","NIM","Nama Lengkap","Hadir","Tugas","Quiz","UTS","UAS","Nilai","Huruf Mutu"};
        int[] lebar = {40,120,220,60,60,60,60,60,60,80};
        Object[][] data = null;
        int nomor=0, baris=0, jbaris=0;
        try{
            dbku.bukaKoneksi();
            dbku.perintah.executeQuery("SELECT * FROM nilai,mahasiswa WHERE (nilai.n_ta_id='"+kodeTA[txtTA.getSelectedIndex()]+"' and nilai.n_ds_id='"+kodeDosen[txtDosen.getSelectedIndex()]+"' and nilai.n_mk_id='"+kodeMK[txtMK.getSelectedIndex()]+"' and mahasiswa.mhs_id=nilai.n_mhs_id)");
            dbku.hasil = dbku.perintah.getResultSet();
            dbku.hasil.last();
            jbaris = dbku.hasil.getRow();

            data = new Object[jbaris][10];
            dbku.hasil.beforeFirst();
            while(dbku.hasil.next()){
                data[nomor][0] = nomor+1;
                data[nomor][1] = dbku.hasil.getString("mhs_id");
                data[nomor][2] = dbku.hasil.getString("mhs_nama");
                data[nomor][3] = dbku.hasil.getString("n_hadir");
                data[nomor][4] = dbku.hasil.getString("n_tugas");
                data[nomor][5] = dbku.hasil.getString("n_quis");
                data[nomor][6] = dbku.hasil.getString("n_mid");
                data[nomor][7] = dbku.hasil.getString("n_final");
                data[nomor][8] = dbku.hasil.getString("n_mutu");
                data[nomor][9] = dbku.hasil.getString("n_huruf");
                nomor+=1;
            }
            //---------------------------------------------------------
            dbku.tutupKoneksi();
            tabelData.setModel(new DefaultTableModel(data, kolom));
            tabelData.setRowHeight(20);
            for(baris=0; baris<kolom.length; baris++){
                tabelData.getColumnModel().getColumn(baris).setPreferredWidth(lebar[baris]);
            }
            tabelData.setVisible(true);
            tabelData.setAutoResizeMode(tabelData.AUTO_RESIZE_OFF);
            jScrollPane1.setViewportView(this.tabelData);

            txtKeterangan.setText("[ Jumlah data : "+jbaris+" ]");
            if(jbaris>0){
                cmdCetak.setEnabled(true);
            }
            else{
                cmdCetak.setEnabled(false);
            }
        }
        catch(SQLException e){JOptionPane.showMessageDialog(this, e.getMessage());}
        catch(Exception e){JOptionPane.showMessageDialog(this, e.getMessage());}
    }

    private void fambilTA()
    {
        Object[] data = null;
        int jdata = 0, no=0;
        try{
            dbku.bukaKoneksi();
            dbku.perintah.executeQuery("SELECT * FROM tahunajar ORDER BY ta_nama ASC");
            dbku.hasil = dbku.perintah.getResultSet();
            dbku.hasil.last();
            jdata = dbku.hasil.getRow();
            data = new Object[jdata];
            kodeTA = new String[jdata];
            dbku.hasil.beforeFirst();
            while(dbku.hasil.next()){
                data[no] = dbku.hasil.getString("ta_nama");
                kodeTA[no] = dbku.hasil.getString("ta_id");
                no++;
            }
            txtTA.setModel(new DefaultComboBoxModel(data));

            // ------------------------ ambil data dosen
            no = 0;
            dbku.perintah.executeQuery("SELECT * FROM dosen ORDER BY ds_nama ASC");
            dbku.hasil = dbku.perintah.getResultSet();
            dbku.hasil.last();
            jdata = dbku.hasil.getRow();
            data = new Object[jdata];
            kodeDosen = new String[jdata];
            dbku.hasil.beforeFirst();
            while(dbku.hasil.next()){
                data[no] = dbku.hasil.getString("ds_nama")+" ("+dbku.hasil.getString("ds_id")+")";
                kodeDosen[no] = dbku.hasil.getString("ds_id");
                no++;
            }
            txtDosen.setModel(new DefaultComboBoxModel(data));

            dbku.tutupKoneksi();
        }
        catch(Exception e){}
    }

    private void fambilMK()
    {
        Object[] data = null;
        int jdata = 0, no=0;
        try{
            dbku.bukaKoneksi();
            dbku.perintah.executeQuery("SELECT * FROM matakuliah ORDER BY mk_nama ASC");
            dbku.hasil = dbku.perintah.getResultSet();
            dbku.hasil.last();
            jdata = dbku.hasil.getRow();
            data = new Object[jdata];
            kodeMK = new String[jdata];
            dbku.hasil.beforeFirst();
            while(dbku.hasil.next()){
                data[no] = dbku.hasil.getString("mk_nama");
                kodeMK[no] = dbku.hasil.getString("mk_id");
                no++;
            }
            dbku.tutupKoneksi();
            txtMK.setModel(new DefaultComboBoxModel(data));
        }
        catch(Exception e){}
    }


    Database dbku = new Database();
    String[] kodeTA = null, kodeMK=null, kodeDosen=null;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdCetak;
    private javax.swing.JButton cmdTutup;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable tabelData;
    private javax.swing.JComboBox txtDosen;
    private javax.swing.JLabel txtKeterangan;
    private javax.swing.JComboBox txtMK;
    private javax.swing.JComboBox txtTA;
    // End of variables declaration//GEN-END:variables

}
