/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * fInputNilai.java
 *
 * Created on 12 Jun 13, 20:02:22
 */

package FACE;

import DB.Database;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Btrans
 */
public class fInputNilai extends javax.swing.JDialog {

    /** Creates new form fInputNilai */
    public fInputNilai(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        fambilMK();
        fambilTA();
        tampilData();
        ftombol(true, false, false, false, false);
        fkolom(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNim = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtHadir = new javax.swing.JTextField();
        txtPersenHadir = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtTugas = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtPersenTugas = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtPersenQuis = new javax.swing.JTextField();
        txtQuis = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtUTS = new javax.swing.JTextField();
        txtPersenUTS = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtUAS = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtPersenUAS = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        cmdTambah = new javax.swing.JButton();
        cmdUbah = new javax.swing.JButton();
        cmdSimpan = new javax.swing.JButton();
        cmdBatal = new javax.swing.JButton();
        cmdHapus = new javax.swing.JButton();
        txtNilaiHadir = new javax.swing.JLabel();
        txtNilaiTugas = new javax.swing.JLabel();
        txtNilaiQuis = new javax.swing.JLabel();
        txtNilaiUTS = new javax.swing.JLabel();
        txtNilaiUAS = new javax.swing.JLabel();
        txtTotal = new javax.swing.JLabel();
        txtHurufMutu = new javax.swing.JLabel();
        txtNama = new javax.swing.JLabel();
        cmdHapus1 = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        txtKeterangan = new javax.swing.JLabel();
        txtMK = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtTA = new javax.swing.JComboBox();
        cmdCari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelData = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDosen = new javax.swing.JComboBox();
        cmdCari1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setForeground(new java.awt.Color(102, 102, 102));
        jTabbedPane1.setFocusable(false);
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 14));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Nomor Induk");

        txtNim.setFont(new java.awt.Font("Tahoma", 0, 12));
        txtNim.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        txtNim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNimActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Nama Lengkap");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Kehadiran");

        txtHadir.setFont(new java.awt.Font("Tahoma", 1, 12));
        txtHadir.setForeground(new java.awt.Color(102, 102, 102));
        txtHadir.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtHadir.setText(" ");

        txtPersenHadir.setBackground(new java.awt.Color(204, 255, 255));
        txtPersenHadir.setFont(new java.awt.Font("Tahoma", 1, 14));
        txtPersenHadir.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtPersenHadir.setText(" ");
        txtPersenHadir.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("x");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("%  =");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Tugas");

        txtTugas.setFont(new java.awt.Font("Tahoma", 1, 12));
        txtTugas.setForeground(new java.awt.Color(102, 102, 102));
        txtTugas.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtTugas.setText(" ");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("x");

        txtPersenTugas.setBackground(new java.awt.Color(204, 255, 255));
        txtPersenTugas.setFont(new java.awt.Font("Tahoma", 1, 14));
        txtPersenTugas.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtPersenTugas.setText(" ");
        txtPersenTugas.setEnabled(false);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("%  =");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("%  =");

        txtPersenQuis.setBackground(new java.awt.Color(204, 255, 255));
        txtPersenQuis.setFont(new java.awt.Font("Tahoma", 1, 14));
        txtPersenQuis.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtPersenQuis.setText(" ");
        txtPersenQuis.setEnabled(false);

        txtQuis.setFont(new java.awt.Font("Tahoma", 1, 12));
        txtQuis.setForeground(new java.awt.Color(102, 102, 102));
        txtQuis.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtQuis.setText(" ");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("x");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("Quiz");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("x");

        txtUTS.setFont(new java.awt.Font("Tahoma", 1, 12));
        txtUTS.setForeground(new java.awt.Color(102, 102, 102));
        txtUTS.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtUTS.setText(" ");

        txtPersenUTS.setBackground(new java.awt.Color(204, 255, 255));
        txtPersenUTS.setFont(new java.awt.Font("Tahoma", 1, 14));
        txtPersenUTS.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtPersenUTS.setText(" ");
        txtPersenUTS.setEnabled(false);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setText("%  =");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("UTS");

        txtUAS.setFont(new java.awt.Font("Tahoma", 1, 12));
        txtUAS.setForeground(new java.awt.Color(102, 102, 102));
        txtUAS.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtUAS.setText(" ");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setText("%  =");

        txtPersenUAS.setBackground(new java.awt.Color(204, 255, 255));
        txtPersenUAS.setFont(new java.awt.Font("Tahoma", 1, 14));
        txtPersenUAS.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtPersenUAS.setText(" ");
        txtPersenUAS.setEnabled(false);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel23.setForeground(new java.awt.Color(102, 102, 102));
        jLabel23.setText("UAS");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel24.setForeground(new java.awt.Color(102, 102, 102));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("x");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel25.setForeground(new java.awt.Color(102, 102, 102));
        jLabel25.setText("Jumlah Total");

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel28.setForeground(new java.awt.Color(102, 102, 102));
        jLabel28.setText("Huruf Mutu");

        cmdTambah.setFont(new java.awt.Font("Tahoma", 1, 12));
        cmdTambah.setForeground(new java.awt.Color(102, 102, 102));
        cmdTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RESS/bg-add.png"))); // NOI18N
        cmdTambah.setText("  ");
        cmdTambah.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdTambahActionPerformed(evt);
            }
        });

        cmdUbah.setFont(new java.awt.Font("Tahoma", 1, 12));
        cmdUbah.setForeground(new java.awt.Color(102, 102, 102));
        cmdUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RESS/edit-pen.png"))); // NOI18N
        cmdUbah.setText("  ");
        cmdUbah.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdUbahActionPerformed(evt);
            }
        });

        cmdSimpan.setFont(new java.awt.Font("Tahoma", 1, 12));
        cmdSimpan.setForeground(new java.awt.Color(102, 102, 102));
        cmdSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RESS/bg-drive-silver.png"))); // NOI18N
        cmdSimpan.setText("  ");
        cmdSimpan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSimpanActionPerformed(evt);
            }
        });

        cmdBatal.setFont(new java.awt.Font("Tahoma", 1, 12));
        cmdBatal.setForeground(new java.awt.Color(102, 102, 102));
        cmdBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RESS/segarkan.png"))); // NOI18N
        cmdBatal.setText("  ");
        cmdBatal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBatalActionPerformed(evt);
            }
        });

        cmdHapus.setFont(new java.awt.Font("Tahoma", 1, 12));
        cmdHapus.setForeground(new java.awt.Color(102, 102, 102));
        cmdHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RESS/trash.png"))); // NOI18N
        cmdHapus.setText("  ");
        cmdHapus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdHapusActionPerformed(evt);
            }
        });

        txtNilaiHadir.setBackground(new java.awt.Color(204, 255, 255));
        txtNilaiHadir.setFont(new java.awt.Font("Tahoma", 1, 14));
        txtNilaiHadir.setForeground(new java.awt.Color(102, 102, 102));
        txtNilaiHadir.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        txtNilaiHadir.setText("0 ");
        txtNilaiHadir.setOpaque(true);

        txtNilaiTugas.setBackground(new java.awt.Color(204, 255, 255));
        txtNilaiTugas.setFont(new java.awt.Font("Tahoma", 1, 14));
        txtNilaiTugas.setForeground(new java.awt.Color(102, 102, 102));
        txtNilaiTugas.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        txtNilaiTugas.setText("0 ");
        txtNilaiTugas.setOpaque(true);

        txtNilaiQuis.setBackground(new java.awt.Color(204, 255, 255));
        txtNilaiQuis.setFont(new java.awt.Font("Tahoma", 1, 14));
        txtNilaiQuis.setForeground(new java.awt.Color(102, 102, 102));
        txtNilaiQuis.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        txtNilaiQuis.setText("0 ");
        txtNilaiQuis.setOpaque(true);

        txtNilaiUTS.setBackground(new java.awt.Color(204, 255, 255));
        txtNilaiUTS.setFont(new java.awt.Font("Tahoma", 1, 14));
        txtNilaiUTS.setForeground(new java.awt.Color(102, 102, 102));
        txtNilaiUTS.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        txtNilaiUTS.setText("0 ");
        txtNilaiUTS.setOpaque(true);

        txtNilaiUAS.setBackground(new java.awt.Color(204, 255, 255));
        txtNilaiUAS.setFont(new java.awt.Font("Tahoma", 1, 14));
        txtNilaiUAS.setForeground(new java.awt.Color(102, 102, 102));
        txtNilaiUAS.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        txtNilaiUAS.setText("0 ");
        txtNilaiUAS.setOpaque(true);

        txtTotal.setBackground(new java.awt.Color(204, 255, 255));
        txtTotal.setFont(new java.awt.Font("Tahoma", 1, 14));
        txtTotal.setForeground(new java.awt.Color(102, 102, 102));
        txtTotal.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        txtTotal.setText("0 ");
        txtTotal.setOpaque(true);

        txtHurufMutu.setBackground(new java.awt.Color(204, 255, 255));
        txtHurufMutu.setFont(new java.awt.Font("Tahoma", 1, 14));
        txtHurufMutu.setForeground(new java.awt.Color(102, 102, 102));
        txtHurufMutu.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        txtHurufMutu.setText("0 ");
        txtHurufMutu.setOpaque(true);

        txtNama.setBackground(new java.awt.Color(204, 255, 255));
        txtNama.setFont(new java.awt.Font("Tahoma", 1, 14));
        txtNama.setForeground(new java.awt.Color(102, 102, 102));
        txtNama.setText("0 ");
        txtNama.setOpaque(true);

        cmdHapus1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmdHapus1.setForeground(new java.awt.Color(102, 102, 102));
        cmdHapus1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RESS/Button-Turn-Off-icon.png"))); // NOI18N
        cmdHapus1.setText("  ");
        cmdHapus1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdHapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdHapus1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtHadir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPersenHadir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNilaiHadir, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtTugas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPersenTugas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNilaiTugas, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtQuis, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPersenQuis, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNilaiQuis, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtUTS, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPersenUTS, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNilaiUTS, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtUAS, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPersenUAS, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNilaiUAS, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                            .addComponent(txtNim, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNama, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                            .addComponent(txtHurufMutu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cmdTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmdHapus1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNim, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNama, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(txtHadir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPersenHadir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(txtNilaiHadir, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(txtTugas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPersenTugas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(txtNilaiTugas, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(txtQuis, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPersenQuis, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(txtNilaiQuis, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(txtUTS, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPersenUTS, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(txtNilaiUTS, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(txtUAS, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPersenUAS, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(txtNilaiUAS, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHurufMutu, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmdTambah, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmdHapus, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                        .addComponent(cmdHapus1, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                    .addComponent(cmdUbah, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                    .addComponent(cmdSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                    .addComponent(cmdBatal, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                .addGap(95, 95, 95))
        );

        jTabbedPane1.addTab("Formulir Masukan Nilai", jPanel2);

        jTabbedPane2.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane2.setForeground(new java.awt.Color(102, 102, 102));
        jTabbedPane2.setFocusable(false);
        jTabbedPane2.setFont(new java.awt.Font("Tahoma", 1, 14));

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));

        txtKeterangan.setBackground(new java.awt.Color(204, 255, 255));
        txtKeterangan.setFont(new java.awt.Font("Tahoma", 1, 12));
        txtKeterangan.setForeground(new java.awt.Color(102, 102, 102));
        txtKeterangan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtKeterangan.setText("[ Jumlah data : 20 ]");
        txtKeterangan.setOpaque(true);

        txtMK.setFont(new java.awt.Font("Tahoma", 0, 12));
        txtMK.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        txtMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMKActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Tahun Ajaran");

        txtTA.setFont(new java.awt.Font("Tahoma", 0, 12));
        txtTA.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        txtTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTAActionPerformed(evt);
            }
        });

        cmdCari.setFont(new java.awt.Font("Tahoma", 1, 12));
        cmdCari.setForeground(new java.awt.Color(102, 102, 102));
        cmdCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RESS/button-search.png"))); // NOI18N
        cmdCari.setText("Lihat Data");
        cmdCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCariActionPerformed(evt);
            }
        });

        tabelData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelData);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Pilih Matakuliah");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Pilih Dosen");

        txtDosen.setFont(new java.awt.Font("Tahoma", 0, 12));
        txtDosen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        txtDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDosenActionPerformed(evt);
            }
        });

        cmdCari1.setFont(new java.awt.Font("Tahoma", 1, 12));
        cmdCari1.setForeground(new java.awt.Color(102, 102, 102));
        cmdCari1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RESS/button-search.png"))); // NOI18N
        cmdCari1.setText("Cari");
        cmdCari1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCari1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtTA, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdCari)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmdCari1))
                    .addComponent(txtMK, 0, 386, Short.MAX_VALUE)
                    .addComponent(txtDosen, 0, 386, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(txtKeterangan, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMK, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTA, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmdCari, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmdCari1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane2.addTab("Nilai Mahasiswa", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNimActionPerformed
        txtNama.setText(kodeNIM[txtNim.getSelectedIndex()]);
    }//GEN-LAST:event_txtNimActionPerformed

    private void cmdCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCariActionPerformed
        tampilData();
        txtMK.setEnabled(true);
        txtTA.setEnabled(true);
        txtDosen.setEnabled(true);
    }//GEN-LAST:event_cmdCariActionPerformed

    private void tabelDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelDataMouseClicked
        if(evt.getClickCount()>0){
            int baris = tabelData.getSelectedRow();
            txtNim.setSelectedItem(tabelData.getValueAt(baris, 1).toString());
            txtNama.setText(tabelData.getValueAt(baris, 2).toString());
            txtHadir.setText(tabelData.getValueAt(baris, 3).toString());
            txtTugas.setText(tabelData.getValueAt(baris, 4).toString());
            txtQuis.setText(tabelData.getValueAt(baris, 5).toString());
            txtUTS.setText(tabelData.getValueAt(baris, 6).toString());
            txtUAS.setText(tabelData.getValueAt(baris, 7).toString());
            txtTotal.setText(tabelData.getValueAt(baris, 8).toString());
            txtHurufMutu.setText(tabelData.getValueAt(baris, 9).toString());
            ftombol(true, true, false, false, true);
            fkolom(false);
            fnilaibersih();
        }
    }//GEN-LAST:event_tabelDataMouseClicked

    private void cmdUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdUbahActionPerformed
        fkolom(true);
        txtNim.setEnabled(false);
        txtHadir.requestFocus();
        ftombol(false, false, true, true, false);
        txtDosen.setEnabled(false);
        txtMK.setEnabled(false);
        txtTA.setEnabled(false);
    }//GEN-LAST:event_cmdUbahActionPerformed

    private void cmdBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBatalActionPerformed
        fkolom(false);
        ftombol(true, false, false, false, false);
        txtDosen.setEnabled(true);
        txtMK.setEnabled(true);
        txtTA.setEnabled(true);
        fbersih();
    }//GEN-LAST:event_cmdBatalActionPerformed

    private void cmdTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdTambahActionPerformed
        fkolom(true);
        txtNim.requestFocus();
        ftombol(false, false, true, true, false);
        txtDosen.setEnabled(false);
        txtMK.setEnabled(false);
        txtTA.setEnabled(false);
        fbersih();
    }//GEN-LAST:event_cmdTambahActionPerformed

    private void cmdSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSimpanActionPerformed
        // deklarasi variabel
        // cek kolom isian
        if(txtNama.getText().isEmpty()){JOptionPane.showMessageDialog(rootPane, "Nim belum terpilih !","Simpan",JOptionPane.WARNING_MESSAGE);txtNama.requestFocus();}
        else if(txtHadir.getText().isEmpty()){JOptionPane.showMessageDialog(rootPane, "Kehadiran belum terisi !","Simpan",JOptionPane.WARNING_MESSAGE); txtHadir.requestFocus();}
        else if(txtTugas.getText().isEmpty()){JOptionPane.showMessageDialog(rootPane, "Tugas belum terisi !","Simpan",JOptionPane.WARNING_MESSAGE); txtTugas.requestFocus();}
        else if(txtQuis.getText().isEmpty()){JOptionPane.showMessageDialog(rootPane, "Quis belum terisi !","Simpan",JOptionPane.WARNING_MESSAGE); txtQuis.requestFocus();}
        else if(txtUTS.getText().isEmpty()){JOptionPane.showMessageDialog(rootPane, "UTS belum terisi !","Simpan",JOptionPane.WARNING_MESSAGE); txtUTS.requestFocus();}
        else if(txtUAS.getText().isEmpty()){JOptionPane.showMessageDialog(rootPane, "UAS belum terisi !","Simpan",JOptionPane.WARNING_MESSAGE); txtUAS.requestFocus();}
        else{
            try{
                // hitung nilai dahulu
                fnilaibersih();
                dbku.bukaKoneksi();
                // cek mode
                if(txtNim.isEnabled()){ // mode tambah
                    // cek nim berdasarkan kode matakuliah dan tahuajaran
                    dbku.perintah.executeQuery("SELECT * FROM nilai WHERE (n_mhs_id='"+txtNim.getSelectedItem()+"' and n_ta_id='"+kodeTA[txtTA.getSelectedIndex()]+"' and n_mk_id='"+kodeMK[txtMK.getSelectedIndex()]+"')");
                    dbku.hasil = dbku.perintah.getResultSet();
                    dbku.hasil.last();
                    // cek apakah data sudah ada atau belum
                    if(dbku.hasil.getRow()>0){
                        JOptionPane.showMessageDialog(rootPane, "Mahasiswa telah didata nilainya, silakan periksa kembali !","Simpan",JOptionPane.WARNING_MESSAGE);
                        txtNim.requestFocus();
                    }
                    else // tidak ada, maka
                    {
                        // simpan data
                        dbku.perintah.execute("INSERT INTO nilai SET n_mhs_id='"+txtNim.getSelectedItem()+"', n_ds_id='"+kodeDosen[txtDosen.getSelectedIndex()]+"', n_mk_id='"+kodeMK[txtMK.getSelectedIndex()]+"', n_ta_id='"+kodeTA[txtTA.getSelectedIndex()]+"', n_hadir='"+txtHadir.getText()+"', n_tugas='"+txtTugas.getText()+"', n_quis='"+txtQuis.getText()+"', n_mid='"+txtUTS.getText()+"', n_final='"+txtUAS.getText()+"', n_mutu='"+txtTotal.getText()+"', n_huruf='"+txtHurufMutu.getText()+"'");
                        JOptionPane.showMessageDialog(rootPane, "Data berhasil disimpan !","Simpan",JOptionPane.INFORMATION_MESSAGE);
                        fbersih();
                        txtNim.requestFocus();
                    }
                    tampilData();
                    fkolom(true);
                    ftombol(false, false, true, true, false);
                }
                else // mode ubah
                {
                        // simpan data
                        dbku.perintah.execute("UPDATE nilai SET n_hadir='"+txtHadir.getText()+"', n_tugas='"+txtTugas.getText()+"', n_quis='"+txtQuis.getText()+"', n_mid='"+txtUTS.getText()+"', n_final='"+txtUAS.getText()+"', n_mutu='"+txtTotal.getText()+"', n_huruf='"+txtHurufMutu.getText()+"' WHERE (n_mhs_id='"+txtNim.getSelectedItem()+"' and n_ta_id='"+kodeTA[txtTA.getSelectedIndex()]+"')");
                        JOptionPane.showMessageDialog(rootPane, "Data berhasil disimpan !","Simpan",JOptionPane.INFORMATION_MESSAGE);
                        ftombol(true, true, false, false, true);
                        tampilData();
                        txtDosen.setEnabled(true);
                        txtMK.setEnabled(true);
                        txtTA.setEnabled(true);
                }
                dbku.tutupKoneksi();
            }
            catch(NumberFormatException e){JOptionPane.showMessageDialog(rootPane, "Ada format inputan yang salah,\nFomat harus angka,\nSilakan periksa kembali !","Masukan",JOptionPane.ERROR_MESSAGE); txtHadir.requestFocus();}
            catch(Exception e){JOptionPane.showMessageDialog(rootPane, "Data gagal disimpan !\n"+e.getMessage());}
        }
    }//GEN-LAST:event_cmdSimpanActionPerformed

    private void cmdHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdHapusActionPerformed
        // konfirmasi penghapusan
        if(JOptionPane.showConfirmDialog(rootPane, "Anda ingin menghapus data nilai berikut :\nNim : "+txtNim.getSelectedItem()+"\nNama Lengkap : "+txtNama.getText()+"\n\nLanjutkan ?","Hapus",JOptionPane.YES_NO_OPTION)==0){
            try{
                dbku.bukaKoneksi();
                dbku.perintah.execute("DELETE FROM nilai WHERE (n_mhs_id='"+txtNim.getSelectedItem()+"' and n_mk_id='"+kodeMK[txtMK.getSelectedIndex()]+"' and n_ta_id='"+kodeTA[txtTA.getSelectedIndex()]+"')");
                JOptionPane.showMessageDialog(rootPane, "Data berhasil dihapus !","Hapus",JOptionPane.INFORMATION_MESSAGE);
                fbersih();
                ftombol(true, false, false, false, false);
                tampilData();
                dbku.tutupKoneksi();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(rootPane, "Data gagal dihapus !\n"+e.getMessage(),"Hapus",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_cmdHapusActionPerformed

    private void cmdHapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdHapus1ActionPerformed
        dispose();
    }//GEN-LAST:event_cmdHapus1ActionPerformed

    private void txtMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMKActionPerformed
        tampilData();
    }//GEN-LAST:event_txtMKActionPerformed

    private void txtDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDosenActionPerformed
        tampilData();
    }//GEN-LAST:event_txtDosenActionPerformed

    private void txtTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTAActionPerformed
        tampilData();
    }//GEN-LAST:event_txtTAActionPerformed

    private void cmdCari1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCari1ActionPerformed
        String cariNim = null;
        cariNim = JOptionPane.showInputDialog(rootPane,"Masukkan Nomor Induk yang ingin dicari : ", "Kotak Pencarian", JOptionPane.QUESTION_MESSAGE);
            String[] kolom = {"No","NIM","Nama Lengkap","Hadir","Tugas","Quiz","UTS","UAS","Nilai","Huruf Mutu"};
        int[] lebar = {40,120,220,60,60,60,60,60,60,80};
        Object[][] data = null;
        int nomor=0, baris=0, jbaris=0;
        try{
            dbku.bukaKoneksi();
            dbku.perintah.executeQuery("SELECT * FROM nilai,mahasiswa WHERE (nilai.n_ta_id='"+kodeTA[txtTA.getSelectedIndex()]+"' and nilai.n_ds_id='"+kodeDosen[txtDosen.getSelectedIndex()]+"' and nilai.n_mk_id='"+kodeMK[txtMK.getSelectedIndex()]+"' and nilai.n_mhs_id='"+cariNim+"' and mahasiswa.mhs_id=nilai.n_mhs_id)");
            dbku.hasil = dbku.perintah.getResultSet();
            dbku.hasil.last();
            jbaris = dbku.hasil.getRow();

            if(jbaris<1){
                JOptionPane.showMessageDialog(rootPane, "Data tidak ditemukan, silakan coba kembali !","Pencarian",JOptionPane.WARNING_MESSAGE);
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "Data ditemukan !","Pencarian",JOptionPane.INFORMATION_MESSAGE);
            }

            data = new Object[jbaris][10];
            dbku.hasil.beforeFirst();
            while(dbku.hasil.next()){
                data[nomor][0] = nomor+1;
                data[nomor][1] = dbku.hasil.getString("mhs_id");
                data[nomor][2] = dbku.hasil.getString("mhs_nama");
                data[nomor][3] = dbku.hasil.getString("n_hadir");
                data[nomor][4] = dbku.hasil.getString("n_tugas");
                data[nomor][5] = dbku.hasil.getString("n_quis");
                data[nomor][6] = dbku.hasil.getString("n_mid");
                data[nomor][7] = dbku.hasil.getString("n_final");
                data[nomor][8] = dbku.hasil.getString("n_mutu");
                data[nomor][9] = dbku.hasil.getString("n_huruf");
                nomor+=1;
            }
            //---------------------------------------------------------
            // ambil persentase dari matakuliah yang ditampilkan
            dbku.perintah.executeQuery("SELECT * FROM persentase WHERE (pr_mk_id='"+kodeMK[txtMK.getSelectedIndex()]+"' and pr_ta_id='"+kodeTA[txtTA.getSelectedIndex()]+"')");
            dbku.hasil = dbku.perintah.getResultSet();
            dbku.hasil.last();
            if(dbku.hasil.getRow()<1){
                JOptionPane.showMessageDialog(rootPane, "Persentase nilai untuk matakuliah ini belum ditentukan, \nsilakan tentukan terlebih dahulu !","Persenatse",JOptionPane.WARNING_MESSAGE);
                ftombol(false, false, false, false, false);
                txtPersenHadir.setText(null);
                txtPersenQuis.setText(null);
                txtPersenTugas.setText(null);
                txtPersenUAS.setText(null);
                txtPersenUTS.setText(null);
            }
            else
            {
                // ambil nilainya
                perseHadir = dbku.hasil.getFloat("pr_hadir");
                persenQuis = dbku.hasil.getFloat("pr_quis");
                persenTugas = dbku.hasil.getFloat("pr_tugas");
                persenUAS = dbku.hasil.getFloat("pr_mid");
                persenUTS = dbku.hasil.getFloat("pr_final");
                // tampilkan dikolom layar
                txtPersenHadir.setText(dbku.hasil.getString("pr_hadir"));
                txtPersenQuis.setText(dbku.hasil.getString("pr_quis"));
                txtPersenTugas.setText(dbku.hasil.getString("pr_tugas"));
                txtPersenUTS.setText(dbku.hasil.getString("pr_mid"));
                txtPersenUAS.setText(dbku.hasil.getString("pr_final"));
            }
            //-------------------------------------------------
            dbku.tutupKoneksi();
            tabelData.setModel(new DefaultTableModel(data, kolom));
            tabelData.setRowHeight(20);
            for(baris=0; baris<kolom.length; baris++){
                tabelData.getColumnModel().getColumn(baris).setPreferredWidth(lebar[baris]);
            }
            tabelData.setVisible(true);
            tabelData.setAutoResizeMode(tabelData.AUTO_RESIZE_OFF);
            jScrollPane1.setViewportView(this.tabelData);
            ftombol(true, false, false, false, false);
            fkolom(false);
            txtKeterangan.setText("[ Jumlah data : "+jbaris+" ]");
        }
        catch(SQLException e){JOptionPane.showMessageDialog(this, e.getMessage());}
        catch(Exception e){JOptionPane.showMessageDialog(this, e.getMessage());}
    }//GEN-LAST:event_cmdCari1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                fInputNilai dialog = new fInputNilai(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void ftombol(boolean t, boolean u, boolean s, boolean b, boolean h){
        cmdTambah.setEnabled(t);
        cmdUbah.setEnabled(u);
        cmdSimpan.setEnabled(s);
        cmdBatal.setEnabled(b);
        cmdHapus.setEnabled(h);
    }

    private void fkolom(boolean aktif){
        txtNim.setEnabled(aktif);
        txtNama.setEnabled(aktif);
        txtHadir.setEditable(aktif);
        txtTugas.setEditable(aktif);
        txtQuis.setEditable(aktif);
        txtUTS.setEditable(aktif);
        txtUAS.setEditable(aktif);
    }

     private void fbersih(){
        txtNim.setSelectedIndex(0);
        txtNama.setText(kodeNIM[txtNim.getSelectedIndex()]);
        txtHadir.setText(null);
        txtTugas.setText(null);
        txtQuis.setText(null);
        txtUTS.setText(null);
        txtUAS.setText(null);
        //-------------------

        txtNilaiHadir.setText(null);
        txtNilaiQuis.setText(null);
        txtNilaiTugas.setText(null);
        txtNilaiUAS.setText(null);
        txtNilaiUTS.setText(null);
        //--------------------------
        txtTotal.setText("");
        txtHurufMutu.setText("");

        /*
         txtPersenHadir.setText(null);
        txtPersenQuis.setText(null);
        txtPersenTugas.setText(null);
        txtPersenUAS.setText(null);
        txtPersenUTS.setText(null);
         */
    }
    
     private void fnilaibersih(){
        float bersihHadir, bersihQuis, bersihTugas, bersihUas, bersihUts;
        nilaiHadir = Float.valueOf(txtHadir.getText());
        nilaiQuis = Float.valueOf(txtQuis.getText());
        nilaiTugas = Float.valueOf(txtTugas.getText());
        nilaiUAS = Float.valueOf(txtUAS.getText());
        nilaiUTS = Float.valueOf(txtUTS.getText());
        // hitung nilai setelah dikali dengan persentase
        bersihHadir = (nilaiHadir*perseHadir)/100;
        bersihQuis = (nilaiQuis*persenQuis)/100;
        bersihTugas = (nilaiTugas*persenTugas)/100;
        bersihUas = (nilaiUAS*persenUAS)/100;
        bersihUts = (nilaiUTS*persenUTS)/100;
        totalNilai = bersihHadir+bersihQuis+bersihTugas+bersihUas+bersihUts;
        // cek kondisinya
        if(totalNilai>=80){hurufMutu="A";}
        else if(totalNilai>=70){hurufMutu="B";}
        else if(totalNilai>=60){hurufMutu="C";}
        else if(totalNilai>=50){hurufMutu="D";}
        else if(totalNilai<=49){hurufMutu="E";}

        // tampilkan nilainya dilayar
        txtNilaiHadir.setText(String.valueOf(bersihHadir));
        txtNilaiQuis.setText(String.valueOf(bersihQuis));
        txtNilaiTugas.setText(String.valueOf(bersihTugas));
        txtNilaiUAS.setText(String.valueOf(bersihUas));
        txtNilaiUTS.setText(String.valueOf(bersihUts));
        txtTotal.setText(String.valueOf(totalNilai));
        txtHurufMutu.setText(hurufMutu);
       
     }

    private void tampilData(){
        String[] kolom = {"No","NIM","Nama Lengkap","Hadir","Tugas","Quiz","UTS","UAS","Nilai","Huruf Mutu"};
        int[] lebar = {40,120,220,60,60,60,60,60,60,80};
        Object[][] data = null;
        int nomor=0, baris=0, jbaris=0;
        try{
            dbku.bukaKoneksi();
            dbku.perintah.executeQuery("SELECT * FROM nilai,mahasiswa WHERE (nilai.n_ta_id='"+kodeTA[txtTA.getSelectedIndex()]+"' and nilai.n_ds_id='"+kodeDosen[txtDosen.getSelectedIndex()]+"' and nilai.n_mk_id='"+kodeMK[txtMK.getSelectedIndex()]+"' and mahasiswa.mhs_id=nilai.n_mhs_id)");
            dbku.hasil = dbku.perintah.getResultSet();
            dbku.hasil.last();
            jbaris = dbku.hasil.getRow();

            data = new Object[jbaris][10];
            dbku.hasil.beforeFirst();
            while(dbku.hasil.next()){
                data[nomor][0] = nomor+1;
                data[nomor][1] = dbku.hasil.getString("mhs_id");
                data[nomor][2] = dbku.hasil.getString("mhs_nama");
                data[nomor][3] = dbku.hasil.getString("n_hadir");
                data[nomor][4] = dbku.hasil.getString("n_tugas");
                data[nomor][5] = dbku.hasil.getString("n_quis");
                data[nomor][6] = dbku.hasil.getString("n_mid");
                data[nomor][7] = dbku.hasil.getString("n_final");
                data[nomor][8] = dbku.hasil.getString("n_mutu");
                data[nomor][9] = dbku.hasil.getString("n_huruf");
                nomor+=1;
            }
            //---------------------------------------------------------
            // ambil persentase dari matakuliah yang ditampilkan
            dbku.perintah.executeQuery("SELECT * FROM persentase WHERE (pr_mk_id='"+kodeMK[txtMK.getSelectedIndex()]+"' and pr_ta_id='"+kodeTA[txtTA.getSelectedIndex()]+"')");
            dbku.hasil = dbku.perintah.getResultSet();
            dbku.hasil.last();
            if(dbku.hasil.getRow()<1){
                JOptionPane.showMessageDialog(rootPane, "Persentase nilai untuk matakuliah ini belum ditentukan, \nsilakan tentukan terlebih dahulu !","Persenatse",JOptionPane.WARNING_MESSAGE);
                ftombol(false, false, false, false, false);
                txtPersenHadir.setText(null);
                txtPersenQuis.setText(null);
                txtPersenTugas.setText(null);
                txtPersenUAS.setText(null);
                txtPersenUTS.setText(null);
            }
            else
            {
                // ambil nilainya
                perseHadir = dbku.hasil.getFloat("pr_hadir");
                persenQuis = dbku.hasil.getFloat("pr_quis");
                persenTugas = dbku.hasil.getFloat("pr_tugas");
                persenUAS = dbku.hasil.getFloat("pr_mid");
                persenUTS = dbku.hasil.getFloat("pr_final");
                // tampilkan dikolom layar
                txtPersenHadir.setText(dbku.hasil.getString("pr_hadir"));
                txtPersenQuis.setText(dbku.hasil.getString("pr_quis"));
                txtPersenTugas.setText(dbku.hasil.getString("pr_tugas"));
                txtPersenUTS.setText(dbku.hasil.getString("pr_mid"));
                txtPersenUAS.setText(dbku.hasil.getString("pr_final"));
            }
            //-------------------------------------------------
            dbku.tutupKoneksi();
            tabelData.setModel(new DefaultTableModel(data, kolom));
            tabelData.setRowHeight(20);
            for(baris=0; baris<kolom.length; baris++){
                tabelData.getColumnModel().getColumn(baris).setPreferredWidth(lebar[baris]);
            }
            tabelData.setVisible(true);
            tabelData.setAutoResizeMode(tabelData.AUTO_RESIZE_OFF);
            jScrollPane1.setViewportView(this.tabelData);
            ftombol(true, false, false, false, false);
            fkolom(false);
            txtKeterangan.setText("[ Jumlah data : "+jbaris+" ]");
        }
        catch(SQLException e){JOptionPane.showMessageDialog(this, e.getMessage());}
        catch(Exception e){JOptionPane.showMessageDialog(this, e.getMessage());}
    }

    private void fambilTA()
    {
        Object[] data = null;
        int jdata = 0, no=0;
        try{
            dbku.bukaKoneksi();
            dbku.perintah.executeQuery("SELECT * FROM tahunajar ORDER BY ta_nama ASC");
            dbku.hasil = dbku.perintah.getResultSet();
            dbku.hasil.last();
            jdata = dbku.hasil.getRow();
            data = new Object[jdata];
            kodeTA = new String[jdata];
            dbku.hasil.beforeFirst();
            while(dbku.hasil.next()){
                data[no] = dbku.hasil.getString("ta_nama");
                kodeTA[no] = dbku.hasil.getString("ta_id");
                no++;
            }
            txtTA.setModel(new DefaultComboBoxModel(data));


            no = 0;
            dbku.perintah.executeQuery("SELECT * FROM mahasiswa ORDER BY mhs_id ASC");
            dbku.hasil = dbku.perintah.getResultSet();
            dbku.hasil.last();
            jdata = dbku.hasil.getRow();
            data = new Object[jdata];
            kodeNIM = new String[jdata];
            dbku.hasil.beforeFirst();
            while(dbku.hasil.next()){
                data[no] = dbku.hasil.getString("mhs_id");
                kodeNIM[no] = dbku.hasil.getString("mhs_nama");
                no++;
            }
            txtNim.setModel(new DefaultComboBoxModel(data));

            no = 0;
            dbku.perintah.executeQuery("SELECT * FROM dosen ORDER BY ds_nama ASC");
            dbku.hasil = dbku.perintah.getResultSet();
            dbku.hasil.last();
            jdata = dbku.hasil.getRow();
            data = new Object[jdata];
            kodeDosen = new String[jdata];
            dbku.hasil.beforeFirst();
            while(dbku.hasil.next()){
                data[no] = dbku.hasil.getString("ds_nama")+" ("+dbku.hasil.getString("ds_id")+")";
                kodeDosen[no] = dbku.hasil.getString("ds_id");
                no++;
            }
            txtDosen.setModel(new DefaultComboBoxModel(data));
            dbku.tutupKoneksi();
        }
        catch(Exception e){}
    }

    private void fambilMK()
    {
        Object[] data = null;
        int jdata = 0, no=0;
        try{
            dbku.bukaKoneksi();
            dbku.perintah.executeQuery("SELECT * FROM matakuliah ORDER BY mk_nama ASC");
            dbku.hasil = dbku.perintah.getResultSet();
            dbku.hasil.last();
            jdata = dbku.hasil.getRow();
            data = new Object[jdata];
            kodeMK = new String[jdata];
            dbku.hasil.beforeFirst();
            while(dbku.hasil.next()){
                data[no] = dbku.hasil.getString("mk_nama");
                kodeMK[no] = dbku.hasil.getString("mk_id");
                no++;
            }
            dbku.tutupKoneksi();
            txtMK.setModel(new DefaultComboBoxModel(data));
        }
        catch(Exception e){}
    }


    Database dbku = new Database();
    String[] kodeTA = null, kodeMK=null, kodeNIM=null, kodeDosen=null;
    float perseHadir=0,persenTugas=0,persenQuis=0,persenUTS=0,persenUAS=0,totalNilai=0;
    float nilaiHadir=0, nilaiTugas=0, nilaiQuis=0, nilaiUTS=0,nilaiUAS=0;
    String hurufMutu="";

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBatal;
    private javax.swing.JButton cmdCari;
    private javax.swing.JButton cmdCari1;
    private javax.swing.JButton cmdHapus;
    private javax.swing.JButton cmdHapus1;
    private javax.swing.JButton cmdSimpan;
    private javax.swing.JButton cmdTambah;
    private javax.swing.JButton cmdUbah;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable tabelData;
    private javax.swing.JComboBox txtDosen;
    private javax.swing.JTextField txtHadir;
    private javax.swing.JLabel txtHurufMutu;
    private javax.swing.JLabel txtKeterangan;
    private javax.swing.JComboBox txtMK;
    private javax.swing.JLabel txtNama;
    private javax.swing.JLabel txtNilaiHadir;
    private javax.swing.JLabel txtNilaiQuis;
    private javax.swing.JLabel txtNilaiTugas;
    private javax.swing.JLabel txtNilaiUAS;
    private javax.swing.JLabel txtNilaiUTS;
    private javax.swing.JComboBox txtNim;
    private javax.swing.JTextField txtPersenHadir;
    private javax.swing.JTextField txtPersenQuis;
    private javax.swing.JTextField txtPersenTugas;
    private javax.swing.JTextField txtPersenUAS;
    private javax.swing.JTextField txtPersenUTS;
    private javax.swing.JTextField txtQuis;
    private javax.swing.JComboBox txtTA;
    private javax.swing.JLabel txtTotal;
    private javax.swing.JTextField txtTugas;
    private javax.swing.JTextField txtUAS;
    private javax.swing.JTextField txtUTS;
    // End of variables declaration//GEN-END:variables

}
