/*
 * fLogin.java
 *
 * Created on 14 Jun 13, 11:00:40
 */

package FACE;

import DB.Database;
import com.jtattoo.plaf.mcwin.McWinLookAndFeel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

public class fLogin extends javax.swing.JDialog {

    /** Creates new form fLogin */
    public fLogin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        // bersihkan kolom
        txtKataSandi.setText(null);
        txtNamaPengguna.setText(null);
        txtNamaPengguna.requestFocus();
        this.setTitle("Sistem Informasi Pendataan Nilai - Masuk");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtNamaPengguna = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmdMasuk = new javax.swing.JButton();
        cmdBatal = new javax.swing.JButton();
        txtKataSandi = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Nama Pengguna");

        txtNamaPengguna.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNamaPengguna.setForeground(new java.awt.Color(102, 102, 102));
        txtNamaPengguna.setText("jTextField1");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Kata Sandi");

        cmdMasuk.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmdMasuk.setForeground(new java.awt.Color(102, 102, 102));
        cmdMasuk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RESS/lanjut.png"))); // NOI18N
        cmdMasuk.setText("Masuk");
        cmdMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMasukActionPerformed(evt);
            }
        });

        cmdBatal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmdBatal.setForeground(new java.awt.Color(102, 102, 102));
        cmdBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RESS/bg-error.png"))); // NOI18N
        cmdBatal.setText("Batal");
        cmdBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBatalActionPerformed(evt);
            }
        });

        txtKataSandi.setForeground(new java.awt.Color(102, 102, 102));
        txtKataSandi.setText("jPasswordField1");

        jLabel1.setBackground(new java.awt.Color(153, 153, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SISTEM INFORMASI PENDATAAN NILAI MAHASISWA");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);

        jLabel4.setBackground(new java.awt.Color(153, 153, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RESS/Apps-preferences-system-login-icon.png"))); // NOI18N
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmdMasuk)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmdBatal)
                            .addComponent(txtKataSandi, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNamaPengguna, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(70, 70, 70))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamaPengguna, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKataSandi, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBatalActionPerformed
        if(JOptionPane.showConfirmDialog(rootPane, "Anda yakin ingin membatalkan proses ?","Keluar",JOptionPane.YES_NO_OPTION)==0){
            System.exit(0);
        }
        else
        {
            txtNamaPengguna.requestFocus();
        }
    }//GEN-LAST:event_cmdBatalActionPerformed

    private void cmdMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMasukActionPerformed
        if(txtNamaPengguna.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Nama pengguna belum terisi, silakan isi dahulu !","Masuk",JOptionPane.WARNING_MESSAGE);
            txtNamaPengguna.requestFocus();
        }
        else if(txtKataSandi.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Kata Sandi belum terisi, silakan isi dahulu !","Masuk",JOptionPane.WARNING_MESSAGE);
            txtKataSandi.requestFocus();
        }
        else
        {
            try{
                dbku.bukaKoneksi();
                dbku.perintah.executeQuery("SELECT * FROM akun WHERE (username='"+txtNamaPengguna.getText()+"' and password='"+txtKataSandi.getText()+"')");
                dbku.hasil = dbku.perintah.getResultSet();
                dbku.hasil.last();
                if(dbku.hasil.getRow()<1){
                    JOptionPane.showMessageDialog(rootPane, "Nama pengguna atau kata sandi Anda salah !","Masuk",JOptionPane.ERROR_MESSAGE);
                    txtNamaPengguna.requestFocus();
                }
                else
                {
                    dispose();
                    new formUtama().setVisible(true);
                }
                dbku.tutupKoneksi();
            }
            catch(Exception e){}
        }
    }//GEN-LAST:event_cmdMasukActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        try{
            UIManager.setLookAndFeel(new McWinLookAndFeel());
        }
        catch(UnsupportedLookAndFeelException e){}

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                fLogin dialog = new fLogin(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    Database dbku = new Database();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBatal;
    private javax.swing.JButton cmdMasuk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField txtKataSandi;
    private javax.swing.JTextField txtNamaPengguna;
    // End of variables declaration//GEN-END:variables

}
