/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * fPersenNilai.java
 *
 * Created on 11 Jun 13, 20:57:11
 */

package FACE;

import DB.Database;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Btrans
 */
public class fPersenNilai extends javax.swing.JDialog {

    /** Creates new form fPersenNilai */
    public fPersenNilai(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        fambilMK();
        fambilTA();
        tampilData();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtTAID = new javax.swing.JComboBox();
        cmdHapus1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelData = new javax.swing.JTable();
        lblJumlah = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtMK = new javax.swing.JComboBox();
        cmdTambah = new javax.swing.JButton();
        cmdUbah = new javax.swing.JButton();
        cmdSimpan = new javax.swing.JButton();
        cmdBatal = new javax.swing.JButton();
        cmdHapus = new javax.swing.JButton();
        cmdTutup = new javax.swing.JButton();
        txtHadir = new javax.swing.JTextField();
        txtTugas = new javax.swing.JTextField();
        txtQuiz = new javax.swing.JTextField();
        txtMid = new javax.swing.JTextField();
        txtFinal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Persentase Nilai Permatakuliah", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(102, 102, 102))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pilih Tahun Ajaran");

        txtTAID.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmdHapus1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmdHapus1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RESS/lanjut.png"))); // NOI18N
        cmdHapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdHapus1ActionPerformed(evt);
            }
        });

        tabelData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelDataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelData);

        lblJumlah.setBackground(new java.awt.Color(204, 255, 255));
        lblJumlah.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblJumlah.setForeground(new java.awt.Color(102, 102, 102));
        lblJumlah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJumlah.setText("[ Jumlah Data : 2 ]");
        lblJumlah.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTAID, 0, 167, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdHapus1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(lblJumlah, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTAID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmdHapus1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detail Persentase Nilai Permatakuliah", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(102, 102, 102))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Matakuliah");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Kehadiran (%)");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tugas (%)");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Quiz (%)");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("UTS (%)");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("UAS (%)");

        txtMK.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        txtMK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMKMouseClicked(evt);
            }
        });
        txtMK.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtMKPropertyChange(evt);
            }
        });

        cmdTambah.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        cmdTambah.setForeground(new java.awt.Color(102, 102, 102));
        cmdTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RESS/bg-add.png"))); // NOI18N
        cmdTambah.setText("Tambah");
        cmdTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdTambahActionPerformed(evt);
            }
        });

        cmdUbah.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        cmdUbah.setForeground(new java.awt.Color(102, 102, 102));
        cmdUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RESS/edit-pen.png"))); // NOI18N
        cmdUbah.setText("Ubah");
        cmdUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdUbahActionPerformed(evt);
            }
        });

        cmdSimpan.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        cmdSimpan.setForeground(new java.awt.Color(102, 102, 102));
        cmdSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RESS/bg-drive-silver.png"))); // NOI18N
        cmdSimpan.setText("Simpan");
        cmdSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSimpanActionPerformed(evt);
            }
        });

        cmdBatal.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        cmdBatal.setForeground(new java.awt.Color(102, 102, 102));
        cmdBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RESS/segarkan.png"))); // NOI18N
        cmdBatal.setText("Batal");
        cmdBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBatalActionPerformed(evt);
            }
        });

        cmdHapus.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        cmdHapus.setForeground(new java.awt.Color(102, 102, 102));
        cmdHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RESS/trash.png"))); // NOI18N
        cmdHapus.setText("Hapus");
        cmdHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdHapusActionPerformed(evt);
            }
        });

        cmdTutup.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        cmdTutup.setForeground(new java.awt.Color(102, 102, 102));
        cmdTutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RESS/Button-Turn-Off-icon.png"))); // NOI18N
        cmdTutup.setText("Tutup");
        cmdTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdTutupActionPerformed(evt);
            }
        });

        txtHadir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtHadir.setForeground(new java.awt.Color(102, 102, 102));
        txtHadir.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtHadir.setText("1");
        txtHadir.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(153, 153, 153)));
        txtHadir.setCaretColor(new java.awt.Color(102, 102, 102));

        txtTugas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtTugas.setForeground(new java.awt.Color(102, 102, 102));
        txtTugas.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtTugas.setText("1");
        txtTugas.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(153, 153, 153)));
        txtTugas.setCaretColor(new java.awt.Color(102, 102, 102));

        txtQuiz.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtQuiz.setForeground(new java.awt.Color(102, 102, 102));
        txtQuiz.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtQuiz.setText("1");
        txtQuiz.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(153, 153, 153)));
        txtQuiz.setCaretColor(new java.awt.Color(102, 102, 102));

        txtMid.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtMid.setForeground(new java.awt.Color(102, 102, 102));
        txtMid.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtMid.setText("1");
        txtMid.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(153, 153, 153)));
        txtMid.setCaretColor(new java.awt.Color(102, 102, 102));

        txtFinal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtFinal.setForeground(new java.awt.Color(102, 102, 102));
        txtFinal.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtFinal.setText("1");
        txtFinal.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(153, 153, 153)));
        txtFinal.setCaretColor(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cmdSimpan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(cmdTambah, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cmdUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmdHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cmdBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmdTutup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMid, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMK, 0, 256, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHadir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTugas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmdTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmdUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmdHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMK, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtHadir, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTugas, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQuiz, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMid, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFinal, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                        .addGap(69, 69, 69)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmdSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmdBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmdTutup, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdTambahActionPerformed
        // TODO add your handling code here:
        // bersihkan kolom
        fbersihText();
        // atur tombol
        ftombol(false, false, true, true, false, false);
        // aktifkan kolom
        fkolom(true);
        // fokuskan kursor
        txtMK.requestFocus();
}//GEN-LAST:event_cmdTambahActionPerformed

    private void cmdUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdUbahActionPerformed
        // TODO add your handling code here:
        // atur tombol
        ftombol(false, false, true, true, false, false);
        // aktifkan kolom
        fkolom(true);
        // fokuskan kursor
        txtHadir.requestFocus();
        // matikan kolom MK
        txtMK.setEnabled(false);
}//GEN-LAST:event_cmdUbahActionPerformed

    private void cmdSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSimpanActionPerformed
        // TODO add your handling code here:
        // cek kolom
        if(txtHadir.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Kehadiran belum terisi, silakan periksa kembali !","Simpan",JOptionPane.WARNING_MESSAGE);
            txtHadir.requestFocus();
        } else if(txtTugas.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Tugas belum terisi, silakan periksa kembali !","Simpan",JOptionPane.WARNING_MESSAGE);
            txtTugas.requestFocus();
        } else if(txtQuiz.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Quiz belum terisi, silakan periksa kembali !","Simpan",JOptionPane.WARNING_MESSAGE);
            txtQuiz.requestFocus();
        } else if(txtMid.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "MidTest belum terisi, silakan periksa kembali !","Simpan",JOptionPane.WARNING_MESSAGE);
            txtMid.requestFocus();
        } else if(txtFinal.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Final belum terisi, silakan periksa kembali !","Simpan",JOptionPane.WARNING_MESSAGE);
            txtFinal.requestFocus();
        } else {
            // cek mode
            try{
                if(txtMK.isEnabled()==true){ // tambah baru
                    dbku.bukaKoneksi();
                    dbku.perintah.executeQuery("SELECT * FROM persentase WHERE pr_ta_id='"+kodeTA[txtTAID.getSelectedIndex()]+"' and pr_mk_id='"+kodeMK[txtMK.getSelectedIndex()]+"'");
                    dbku.hasil = dbku.perintah.getResultSet();
                    dbku.hasil.last();
                    if(dbku.hasil.getRow()>0){
                        JOptionPane.showMessageDialog(rootPane, "Matakuliah "+txtMK.getSelectedItem()+" di semester "+txtTAID.getSelectedItem()+" sudah ada !","Simpan",JOptionPane.WARNING_MESSAGE);
                        txtMK.requestFocus();
                    } else {
                        // simpan
                       
                        dbku.perintah.execute("INSERT INTO persentase SET " +
                                "pr_mk_id='"+kodeMK[txtMK.getSelectedIndex()]+"', " +
                                "pr_ta_id='"+kodeTA[txtTAID.getSelectedIndex()]+"', " +
                                "pr_hadir='"+txtHadir.getText()+"'," +
                                "pr_tugas='"+txtTugas.getText()+"'," +
                                "pr_quis='"+txtQuiz.getText()+"'," +
                                "pr_mid='"+txtMid.getText()+"'," +
                                "pr_final='"+txtFinal.getText()+"'");
                        JOptionPane.showMessageDialog(rootPane, "Data berhasil disimpan !","Simpan",JOptionPane.INFORMATION_MESSAGE);
                        // bersih
                        fbersihText();
                        // fokus ke mk
                        txtMK.requestFocus();
                        // tampil data
                        tampilData();
                    }
                    dbku.tutupKoneksi();
                } else{ // ubah data
                    dbku.bukaKoneksi();
                    
                    dbku.perintah.execute("UPDATE persentase SET " +
                                "pr_hadir='"+txtHadir.getText()+"'," +
                                "pr_tugas='"+txtTugas.getText()+"'," +
                                "pr_quis='"+txtQuiz.getText()+"'," +
                                "pr_mid='"+txtMid.getText()+"'," +
                                "pr_final='"+txtFinal.getText()+"'" +
                            "WHERE pr_mk_id='"+kodeMK[txtMK.getSelectedIndex()]+"' and pr_ta_id='"+kodeTA[txtTAID.getSelectedIndex()]+"'");
                    JOptionPane.showMessageDialog(rootPane, "Data berhasil disimpan !","Simpan",JOptionPane.INFORMATION_MESSAGE);
                    // kunci isian
                    fkolom(false);
                    // tombol
                    ftombol(true, true, false, false, true, true);
                    // tampil tabel
                    tampilData();
                    dbku.tutupKoneksi();
                }
            } catch(Exception e){JOptionPane.showMessageDialog(rootPane, e.getMessage());}
        }
}//GEN-LAST:event_cmdSimpanActionPerformed

    private void cmdBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBatalActionPerformed
        // TODO add your handling code here:
        // atur tombol
        ftombol(true, false, false, false, false, true);
        // matikan kolom
        fkolom(false);
        // bersihkan kolom
        fbersihText();
        // fokuskan ke tombol tambah
        cmdTambah.requestFocus();
}//GEN-LAST:event_cmdBatalActionPerformed

    private void cmdHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdHapusActionPerformed
        // TODO add your handling code here:
        // ambil baris
        int baris = tabelData.getSelectedRow();
        try{
            if(JOptionPane.showConfirmDialog(rootPane, "Hapus data Matakuliah "+txtMK.getSelectedItem()+" ?","Hapus", JOptionPane.YES_NO_OPTION)==0){
                dbku.bukaKoneksi();
                dbku.perintah.execute("DELETE FROM persentase WHERE pr_mk_id='"+kodeMK[txtMK.getSelectedIndex()]+"' and pr_ta_id='"+kodeTA[txtTAID.getSelectedIndex()]+"'");
                dbku.tutupKoneksi();
                JOptionPane.showMessageDialog(rootPane, "Data berhasil dihapus !","Hapus",JOptionPane.INFORMATION_MESSAGE);
                // bersih
                fbersihText();
                // atur tombol
                ftombol(true, false, false, false, false, true);
                // fokuskan ke tambah
                cmdTambah.requestFocus();
                tampilData();
            }
        } catch(Exception e){}
}//GEN-LAST:event_cmdHapusActionPerformed

    private void cmdTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdTutupActionPerformed
        dispose();
}//GEN-LAST:event_cmdTutupActionPerformed

    private void cmdHapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdHapus1ActionPerformed
        // TODO add your handling code here:
        tampilData();
        // bersihkan kolom
        fbersihText();
    }//GEN-LAST:event_cmdHapus1ActionPerformed

    private void tabelDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelDataMouseClicked
        // TODO add your handling code here:
        int brs = tabelData.getSelectedRow();
        if(evt.getClickCount()>0){
            txtMK.setSelectedItem(tabelData.getValueAt(brs, 2));
            txtHadir.setText(tabelData.getValueAt(brs, 3).toString());
            txtTugas.setText(tabelData.getValueAt(brs, 4).toString());
            txtQuiz.setText(tabelData.getValueAt(brs, 5).toString());
            txtMid.setText(tabelData.getValueAt(brs, 6).toString());
            txtFinal.setText(tabelData.getValueAt(brs, 7).toString());
            ftombol(true, true, false, false, true, true);
            fkolom(false);
        }
    }//GEN-LAST:event_tabelDataMouseClicked

    private void txtMKPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtMKPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMKPropertyChange

    private void txtMKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMKMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMKMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowActivated

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowGainedFocus

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                fPersenNilai dialog = new fPersenNilai(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void fbersihText(){
        txtMK.setSelectedIndex(0);
        txtHadir.setText("0");
        txtTugas.setText("0");
        txtQuiz.setText("0");
        txtMid.setText("0");
        txtFinal.setText("0");
    }

    private void ftombol(boolean t, boolean u, boolean s, boolean b, boolean h, boolean tu){
        cmdTambah.setEnabled(t);
        cmdUbah.setEnabled(u);
        cmdSimpan.setEnabled(s);
        cmdBatal.setEnabled(b);
        cmdHapus.setEnabled(h);
        cmdTutup.setEnabled(tu);
    }

    private void fkolom(boolean aktif){
        txtMK.setEnabled(aktif);
        txtHadir.setEditable(aktif);
        txtTugas.setEditable(aktif);
        txtQuiz.setEditable(aktif);
        txtMid.setEditable(aktif);
        txtFinal.setEditable(aktif);
    }

    private void tampilData(){
        String[] kolom = {"No","Kode MK","Matakuliah","Hadir(%)","Tugas(%)","Quiz(%)","MidTest(%)","Final(%)"};
        int[] lebar = {40,120,220,60,60,60,60,60};
        Object[][] data = null;
        int nomor=0, baris=0, jbaris=0;
        try{
            dbku.bukaKoneksi();
            dbku.perintah.executeQuery("SELECT * FROM persentase,matakuliah WHERE (persentase.pr_ta_id='"+kodeTA[txtTAID.getSelectedIndex()]+"' and matakuliah.mk_id=persentase.pr_mk_id)");
            dbku.hasil = dbku.perintah.getResultSet();
            dbku.hasil.last();
            jbaris = dbku.hasil.getRow();
            data = new Object[jbaris][8];
            dbku.hasil.beforeFirst();
            while(dbku.hasil.next()){
                data[nomor][0] = nomor+1;
                data[nomor][1] = dbku.hasil.getString("mk_id");
                data[nomor][2] = dbku.hasil.getString("mk_nama");
                data[nomor][3] = dbku.hasil.getString("pr_hadir");
                data[nomor][4] = dbku.hasil.getString("pr_tugas");
                data[nomor][5] = dbku.hasil.getString("pr_quis");
                data[nomor][6] = dbku.hasil.getString("pr_mid");
                data[nomor][7] = dbku.hasil.getString("pr_final");
                nomor+=1;
            }
            dbku.tutupKoneksi();
            tabelData.setModel(new DefaultTableModel(data, kolom));
            tabelData.setRowHeight(20);
            for(baris=0; baris<kolom.length; baris++){
                tabelData.getColumnModel().getColumn(baris).setPreferredWidth(lebar[baris]);
            }
            tabelData.setVisible(true);
            tabelData.setAutoResizeMode(tabelData.AUTO_RESIZE_OFF);
            jScrollPane2.setViewportView(this.tabelData);
            ftombol(true, false, false, false, false, true);
            fkolom(false);
            lblJumlah.setText("[ Jumlah data : "+jbaris+" ]");
        }
        catch(SQLException e){JOptionPane.showMessageDialog(this, e.getMessage());}
        catch(Exception e){JOptionPane.showMessageDialog(this, e.getMessage());}
    }

    String[] kodeTA = null, kodeMK=null;
    private void fambilTA()
    {
        Object[] data = null;
        int jdata = 0, no=0;
        try{
            dbku.bukaKoneksi();
            dbku.perintah.executeQuery("SELECT * FROM tahunajar ORDER BY ta_nama ASC");
            dbku.hasil = dbku.perintah.getResultSet();
            dbku.hasil.last();
            jdata = dbku.hasil.getRow();
            data = new Object[jdata];
            kodeTA = new String[jdata];
            dbku.hasil.beforeFirst();
            while(dbku.hasil.next()){
                data[no] = dbku.hasil.getString("ta_nama");
                kodeTA[no] = dbku.hasil.getString("ta_id");
                no++;
            }
            dbku.tutupKoneksi();
            txtTAID.setModel(new DefaultComboBoxModel(data));
        }
        catch(Exception e){}
    }

    private void fambilMK()
    {
        Object[] data = null;
        int jdata = 0, no=0;
        try{
            dbku.bukaKoneksi();
            dbku.perintah.executeQuery("SELECT * FROM matakuliah ORDER BY mk_nama ASC");
            dbku.hasil = dbku.perintah.getResultSet();
            dbku.hasil.last();
            jdata = dbku.hasil.getRow();
            data = new Object[jdata];
            kodeMK = new String[jdata];
            dbku.hasil.beforeFirst();
            while(dbku.hasil.next()){
                data[no] = dbku.hasil.getString("mk_nama");
                kodeMK[no] = dbku.hasil.getString("mk_id");
                no++;
            }
            dbku.tutupKoneksi();
            txtMK.setModel(new DefaultComboBoxModel(data));
        }
        catch(Exception e){}
    }


    Database dbku = new Database();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBatal;
    private javax.swing.JButton cmdHapus;
    private javax.swing.JButton cmdHapus1;
    private javax.swing.JButton cmdSimpan;
    private javax.swing.JButton cmdTambah;
    private javax.swing.JButton cmdTutup;
    private javax.swing.JButton cmdUbah;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblJumlah;
    private javax.swing.JTable tabelData;
    private javax.swing.JTextField txtFinal;
    private javax.swing.JTextField txtHadir;
    private javax.swing.JComboBox txtMK;
    private javax.swing.JTextField txtMid;
    private javax.swing.JTextField txtQuiz;
    private javax.swing.JComboBox txtTAID;
    private javax.swing.JTextField txtTugas;
    // End of variables declaration//GEN-END:variables

}
